FROM alpine:latest AS builder

RUN --mount=type=cache,id=apk-cache,sharing=locked,target=/var/cache/apk \
  apk --update add ruby bash git build-base ruby-dev libffi-dev

WORKDIR /site
COPY site/Gemfile* /site/

RUN --mount=type=cache,target=/root/.gem \
  gem install bundler && bundle install --frozen

ENTRYPOINT [ "bundle", "exec", "jekyll" ]
CMD ["serve", "--incremental", "--host=0.0.0.0", "--watch", "--drafts", "--force_polling", "--livereload"]
